[package]
name = "rust-basic-asyncwebserver"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
tera = "1.11.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
